# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]=#040504

# Main text color
theme[main_fg]=#e3e2de

# Title color for boxes
theme[title]=#e3e2de

# Highlight color for keyboard shortcuts
theme[hi_fg]=#b5cea9

# Background color of selected item in processes box
theme[selected_bg]=#090908

# Foreground color of selected item in processes box
theme[selected_fg]=#b5cea9

# Color of inactive/disabled text
theme[inactive_fg]=#8e9288

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]=#a4ced0

# Background color of the percentage meters
theme[meter_bg]=#8e9288

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]=#a4ced0

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]=#5bd0df
theme[mem_box]=#b8eea6
theme[net_box]=#c6c177
theme[proc_box]=#70cfa2

# Box divider line and small boxes line color
theme[div_line]=#444840

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]=#b8eea6
theme[temp_mid]=#e7f7cc
theme[temp_end]=#c5b542

# CPU graph colors (Teal -> Sapphire -> Lavender)
theme[cpu_start]=#b7edb8
theme[cpu_mid]=#8bd8a6
theme[cpu_end]=#89dcc6

# Mem/Disk free meter (Mauve -> Lavender -> Blue)
theme[free_start]=#5bd0df
theme[free_mid]=#89dcc6
theme[free_end]=#70cfa2

# Mem/Disk cached meter (Sapphire -> Blue -> Lavender)
theme[cached_start]=#8bd8a6
theme[cached_mid]=#70cfa2
theme[cached_end]=#89dcc6

# Mem/Disk available meter (Peach -> Maroon -> Red)
theme[available_start]=#c5d590
theme[available_mid]=#c6c177
theme[available_end]=#c5b542

# Mem/Disk used meter (Green -> Teal -> Sky)
theme[used_start]=#b8eea6
theme[used_mid]=#b7edb8
theme[used_end]=#aaeab8

# Download graph colors (Peach -> Maroon -> Red)
theme[download_start]=#c5d590
theme[download_mid]=#c6c177
theme[download_end]=#c5b542

# Upload graph colors (Green -> Teal -> Sky)
theme[upload_start]=#b8eea6
theme[upload_mid]=#b7edb8
theme[upload_end]=#aaeab8

# Process box color gradient for threads, mem and cpu usage (Sapphire -> Lavender -> Mauve)
theme[process_start]=#8bd8a6
theme[process_mid]=#89dcc6
theme[process_end]=#5bd0df
