context.properties = {
  default.clock.rate          = 48000
  default.clock.allowed-rates = [ 48000 ]
  default.clock.quantum       = 2048
  default.clock.min-quantum   = 2048
  # ponytail: no max-quantum so the BT driver can use its native ~2048 quantum
}

