$background = 050302
$onBackground = f9e0da
$surface = 050302
$surfaceDim = 050302
$surfaceBright = 130b09
$surfaceContainerLowest = 000000
$surfaceContainerLow = 080303
$surfaceContainer = 0c0504
$surfaceContainerHigh = 0e0706
$surfaceContainerHighest = 110907
$onSurface = f9e0da
$surfaceVariant = 110907
$onSurfaceVariant = bca6a1
$outline = 84716c
$outlineVariant = 554440
$inverseSurface = fff8f6
$inverseOnSurface = 5d5350
$shadow = 000000
$scrim = 000000
$surfaceTint = 38231c
$primary = f9b7a4
$primaryDim = eaaa97
$onPrimary = 613427
$primaryContainer = 764638
$onPrimaryContainer = ffdcd2
$inversePrimary = 855243
$primaryFixed = ffbcaa
$primaryFixedDim = f0af9d
$onPrimaryFixed = 4e2519
$onPrimaryFixedVariant = 704033
$secondary = e7bdb2
$secondaryDim = d8b0a5
$onSecondary = 563931
$secondaryContainer = 50352d
$onSecondaryContainer = dfb6ab
$secondaryFixed = ffdbd1
$secondaryFixedDim = f6cbbf
$onSecondaryFixed = 553830
$onSecondaryFixedVariant = 74544b
$tertiary = ffe8c4
$tertiaryDim = fdd896
$onTertiary = 6d531e
$tertiaryContainer = fdd896
$onTertiaryContainer = 634a16
$tertiaryFixed = fdd896
$tertiaryFixedDim = eeca89
$onTertiaryFixed = 4f3804
$onTertiaryFixedVariant = 6e541f
$error = fa746f
$errorDim = c54d4a
$onError = 490006
$errorContainer = 871f21
$onErrorContainer = ff9993
$primaryPaletteKeyColor = a06959
$secondaryPaletteKeyColor = 926f65
$tertiaryPaletteKeyColor = 90733b
$neutralPaletteKeyColor = 807471
$neutralVariantPaletteKeyColor = 86736e
$errorPaletteKeyColor = c84f4c
$primary_paletteKeyColor = a06959
$secondary_paletteKeyColor = 926f65
$tertiary_paletteKeyColor = 90733b
$neutral_paletteKeyColor = 807471
$neutral_variant_paletteKeyColor = 86736e
$term0 = 080808
$term1 = ff572a
$term2 = ffbe97
$term3 = ffdfd2
$term4 = b9ab66
$term5 = f29082
$term6 = ffbb85
$term7 = efd2c7
$term8 = b49e96
$term9 = ff8766
$term10 = ffd5bd
$term11 = fff1ec
$term12 = dcbc93
$term13 = ffa99a
$term14 = ffd2b4
$term15 = ffffff
$rosewater = ffeeea
$flamingo = ffd9d1
$pink = ffd3ce
$mauve = ffa9aa
$red = ff9886
$maroon = faab9b
$peach = ffbfa9
$yellow = ffeee7
$green = ffd8bd
$teal = ffdb94
$sky = e1df87
$sapphire = f2b2f2
$blue = ffa2bd
$lavender = ffbbc2
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cf5c5c
$kvisitedSelection = cf5c5f
$knegative = ea5636
$knegativeSelection = ea5639
$kneutral = ff8a60
$kneutralSelection = ff8a63
$kpositive = f98e1c
$kpositiveSelection = fa8e20
$text = f9e0da
$subtext1 = bca6a1
$subtext0 = 84716c
$overlay2 = 1a1818
$overlay1 = 171515
$overlay0 = 151212
$surface2 = 110f0e
$surface1 = 0d0a09
$surface0 = 060403
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
