--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
--enable-gpu-rasterization
--enable-zero-copy
--ignore-gpu-blocklist
--enable-accelerated-mjpeg-decode
--enable-accelerated-video
--enable-native-gpu-memory-buffers
--use-vulkan
